import JSZip from "jszip";

export async function buildBundleZip(input: {
  dockerfile: string;
  githubActionsYaml: string;
  doAppSpecYaml: string;
  repoUrl: string;
  framework: string;
}): Promise<{ filename: string; base64: string }> {
  const zip = new JSZip();

  // root files
  zip.file("Dockerfile", input.dockerfile);
  zip.file("do-app.yaml", input.doAppSpecYaml);

  const readme = `
# DeployMate Bundle

Repo: ${input.repoUrl}
Detected framework: ${input.framework}

## Contents
- Dockerfile (build + run container)
- do-app.yaml (DigitalOcean App Platform spec)
- .github/workflows/deploymate.yml (CI build workflow)

## How to use
1) Copy these files into your repo root.
2) Commit & push.
3) In DigitalOcean App Platform:
   - Create App from GitHub repo
   - Use Dockerfile
   - (Optional) Use do-app.yaml as spec reference

Generated by DeployMate.
`.trim();

  zip.file("DEPLOYMATE_README.md", readme);

  // GitHub Actions workflow path
  zip
    .folder(".github")
    ?.folder("workflows")
    ?.file("deploymate.yml", input.githubActionsYaml);

  const base64 = await zip.generateAsync({ type: "base64" });
  return { filename: "deploymate-bundle.zip", base64 };
}
